# Generated by Django 5.1.6 on 2025-02-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
