# Generated by Django 5.1.6 on 2025-02-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent', models.DecimalField(decimal_places=0, max_digits=2)),
                ('status', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='images/offers/')),
                ('is_visible', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ('sort', 'name')},
        ),
    ]
