# Generated by Django 5.1.6 on 2025-02-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_offer_alter_about_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Off', 'Off'), ('On', 'On')], default='Off', max_length=3),
        ),
    ]
