# Generated by Django 5.1.6 on 2025-02-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_offer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=500)),
                ('photo', models.ImageField(upload_to='images/clients/')),
                ('grade', models.CharField(choices=[('Great', 'Great'), ('Average', 'Average'), ('Bad', 'Bad')], default='Average', max_length=7)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('sort', 'name'),
            },
        ),
    ]
