# Generated by Django 5.1.6 on 2025-02-20 12:14

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_contactinfo_email_alter_contactinfo_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator(message='Invalid email address')])),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('date', models.DateField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='opening_hours',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
